sudo: false

language: python

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35

env:
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=flake8

install: pip install -U tox

script: tox
